insert into anios (anio, descripcion) values (1, 'Tetebatu');
insert into anios (anio, descripcion) values (2, 'Bengga');
insert into anios (anio, descripcion) values (3, 'Shengci');
insert into anios (anio, descripcion) values (4, 'Igbeti');
insert into anios (anio, descripcion) values (5, 'Heshan');
insert into anios (anio, descripcion) values (6, 'Benjamín Aceval');
insert into anios (anio, descripcion) values (7, 'Krajan Sumberanget');
insert into anios (anio, descripcion) values (8, 'Angoulême');
insert into anios (anio, descripcion) values (9, 'Guanyang');
insert into anios (anio, descripcion) values (10, 'Minato');
insert into anios (anio, descripcion) values (11, 'Silva Jardim');
insert into anios (anio, descripcion) values (12, 'Ciburial');
insert into anios (anio, descripcion) values (13, 'Čair');
insert into anios (anio, descripcion) values (14, 'Singojuruh');
insert into anios (anio, descripcion) values (15, 'Lyubertsy');
insert into anios (anio, descripcion) values (16, 'Kanginan');
insert into anios (anio, descripcion) values (17, 'Velagići');
insert into anios (anio, descripcion) values (18, 'Pescara');
insert into anios (anio, descripcion) values (19, 'Haokou');
insert into anios (anio, descripcion) values (20, 'Padangbatung');
insert into anios (anio, descripcion) values (21, 'Santa Rosa');
insert into anios (anio, descripcion) values (22, 'Severobaykal’sk');
insert into anios (anio, descripcion) values (23, 'Fulu');
insert into anios (anio, descripcion) values (24, 'Stockholm');
insert into anios (anio, descripcion) values (25, 'La Victoria');
insert into anios (anio, descripcion) values (26, 'Reggio Calabria');
insert into anios (anio, descripcion) values (27, 'Dolní Čermná');
insert into anios (anio, descripcion) values (28, 'Rennes');
insert into anios (anio, descripcion) values (29, 'Itaocara');
insert into anios (anio, descripcion) values (30, 'Cunha');
insert into anios (anio, descripcion) values (31, 'Raymond');
insert into anios (anio, descripcion) values (32, 'Daqin Tal');
insert into anios (anio, descripcion) values (33, 'Łyse');
insert into anios (anio, descripcion) values (34, 'Saraktash');
insert into anios (anio, descripcion) values (35, 'Holoubkov');
insert into anios (anio, descripcion) values (36, 'El Ingenio');
insert into anios (anio, descripcion) values (37, 'Lendangara Satu');
insert into anios (anio, descripcion) values (38, 'Maintirano');
insert into anios (anio, descripcion) values (39, 'Chita');
insert into anios (anio, descripcion) values (40, 'Chociwel');
insert into anios (anio, descripcion) values (41, 'Eskilstuna');
insert into anios (anio, descripcion) values (42, 'Luna');
insert into anios (anio, descripcion) values (43, 'Ipatinga');
insert into anios (anio, descripcion) values (44, 'Manogay');
insert into anios (anio, descripcion) values (45, 'Banjar Mambalkajanan');
insert into anios (anio, descripcion) values (46, 'Przelewice');
insert into anios (anio, descripcion) values (47, 'San Carlos');
insert into anios (anio, descripcion) values (48, 'Rizal');
insert into anios (anio, descripcion) values (49, 'Kallithéa');
insert into anios (anio, descripcion) values (50, 'Tomakivka');
insert into anios (anio, descripcion) values (51, 'Marseille');
insert into anios (anio, descripcion) values (52, 'Rimbo');
insert into anios (anio, descripcion) values (53, 'Guadalupe');
insert into anios (anio, descripcion) values (54, 'Liaozhong');
insert into anios (anio, descripcion) values (55, 'Mlaka pri Kranju');
insert into anios (anio, descripcion) values (56, 'Castañas');
insert into anios (anio, descripcion) values (57, 'Dobra');
insert into anios (anio, descripcion) values (58, 'Argir');
insert into anios (anio, descripcion) values (59, 'Gagarin');
insert into anios (anio, descripcion) values (60, 'Allen');
insert into anios (anio, descripcion) values (61, 'Sankwia');
insert into anios (anio, descripcion) values (62, 'Azteca');
insert into anios (anio, descripcion) values (63, 'Águas Formosas');
insert into anios (anio, descripcion) values (64, 'San Jerónimo');
insert into anios (anio, descripcion) values (65, 'Karanggintung');
insert into anios (anio, descripcion) values (66, 'Sidomulyo');
insert into anios (anio, descripcion) values (67, 'Saint-Maur-des-Fossés');
insert into anios (anio, descripcion) values (68, 'Pristina');
insert into anios (anio, descripcion) values (69, 'Chile Chico');
insert into anios (anio, descripcion) values (70, 'Laguna de Perlas');
insert into anios (anio, descripcion) values (71, 'Esperanza');
insert into anios (anio, descripcion) values (72, 'Roanne');
insert into anios (anio, descripcion) values (73, 'Ocumare del Tuy');
insert into anios (anio, descripcion) values (74, 'Krynice');
insert into anios (anio, descripcion) values (75, 'Doāba');
insert into anios (anio, descripcion) values (76, 'Okulovka');
insert into anios (anio, descripcion) values (77, 'Carayaó');
insert into anios (anio, descripcion) values (78, 'Igarapé Miri');
insert into anios (anio, descripcion) values (79, 'Gorzyce');
insert into anios (anio, descripcion) values (80, 'Bangkalan');
insert into anios (anio, descripcion) values (81, 'Belén');
insert into anios (anio, descripcion) values (82, 'Ajdabiya');
insert into anios (anio, descripcion) values (83, 'Aracaju');
insert into anios (anio, descripcion) values (84, 'Casal de São João');
insert into anios (anio, descripcion) values (85, 'Waegwan');
insert into anios (anio, descripcion) values (86, 'Masachapa');
insert into anios (anio, descripcion) values (87, 'Paris 15');
insert into anios (anio, descripcion) values (88, 'Szczecin');
insert into anios (anio, descripcion) values (89, 'Tynne');
insert into anios (anio, descripcion) values (90, 'Qaxbaş');
insert into anios (anio, descripcion) values (91, 'Gaocheng');
insert into anios (anio, descripcion) values (92, 'Jinling');
insert into anios (anio, descripcion) values (93, 'Boulogne-Billancourt');
insert into anios (anio, descripcion) values (94, 'Tarragona');
insert into anios (anio, descripcion) values (95, 'Maclear');
insert into anios (anio, descripcion) values (96, 'Xuebu');
insert into anios (anio, descripcion) values (97, 'Ning’an');
insert into anios (anio, descripcion) values (98, 'Marovoay');
insert into anios (anio, descripcion) values (99, 'Verkhnevilyuysk');
insert into anios (anio, descripcion) values (100, 'Mlalo');
