insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Palekastro', '17543 Washington Pass', 'Khaki', 'Citambal', 'Turquoise', 'Turquoise');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Wudui', '770 North Terrace', 'Crimson', 'Mandal', 'Blue', 'Blue');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Ndano', '48 Carpenter Parkway', 'Violet', 'Salamá', 'Khaki', 'Indigo');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Montpellier', '99606 Corben Court', 'Khaki', 'Carreira', 'Mauv', 'Turquoise');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Oyam', '72 Del Sol Park', 'Khaki', 'Ḩadīdah', 'Goldenrod', 'Orange');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Stockholm', '21862 Novick Park', 'Aquamarine', 'Jinrongjie', 'Purple', 'Khaki');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Östhammar', '5792 Basil Junction', 'Maroon', 'Jeziorany', 'Violet', 'Khaki');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Jackson', '4 Elka Trail', 'Blue', 'Mandala', 'Fuscia', 'Maroon');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Gaolong', '6 Warrior Court', 'Goldenrod', 'Chagou', 'Violet', 'Teal');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Quinchía', '5879 Farmco Plaza', 'Goldenrod', 'Xinxu', 'Mauv', 'Puce');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Eskilstuna', '66 Mcguire Street', 'Violet', 'Zhouxi', 'Crimson', 'Yellow');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Shuanghe', '77139 Kinsman Court', 'Yellow', 'Carahue', 'Indigo', 'Khaki');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Fotolívos', '3 Gateway Pass', 'Teal', 'Capalonga', 'Aquamarine', 'Mauv');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Zhoupu', '57 Monterey Place', 'Fuscia', 'Dassun', 'Teal', 'Khaki');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Thành Phố Lạng Sơn', '717 Florence Hill', 'Goldenrod', 'Kangmei', 'Violet', 'Red');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Junín', '5959 Warner Park', 'Fuscia', 'Yong’an', 'Pink', 'Crimson');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Klumpit', '2873 Vidon Way', 'Crimson', 'Predavac', 'Goldenrod', 'Blue');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Curridabat', '630 Bonner Court', 'Orange', 'Katsina-Ala', 'Goldenrod', 'Purple');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Promissão', '032 Esker Pass', 'Purple', 'Szczawnica', 'Pink', 'Blue');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Ferkessédougou', '79 Ryan Street', 'Violet', 'Beloha', 'Yellow', 'Orange');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Polyarnyy', '1 Cordelia Avenue', 'Fuscia', 'Pampamarca', 'Blue', 'Crimson');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Murtajih', '5 Buena Vista Terrace', 'Turquoise', 'Chandal Bā’ī', 'Pink', 'Green');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Féres', '7189 Badeau Road', 'Orange', 'Taoyuan', 'Maroon', 'Indigo');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Cengang', '05249 Blackbird Park', 'Aquamarine', 'Porteirinha', 'Aquamarine', 'Turquoise');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Brudzeń Duży', '0306 Dawn Place', 'Teal', 'Santana do Livramento', 'Purple', 'Fuscia');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Ciakar', '0 Oneill Crossing', 'Maroon', 'Chambéry', 'Red', 'Pink');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Pont-Rouge', '94344 Lerdahl Avenue', 'Khaki', 'Vila Chã', 'Crimson', 'Crimson');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Nunbaundelha', '53 Menomonie Avenue', 'Blue', 'Ambatofinandrahana', 'Red', 'Blue');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Sakhnīn', '49047 Kedzie Court', 'Puce', 'Aoji-ri', 'Yellow', 'Aquamarine');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Täby', '28597 Packers Court', 'Purple', 'Guaçuí', 'Fuscia', 'Red');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Oravais', '5 Mesta Point', 'Crimson', 'Xiwanzi', 'Blue', 'Maroon');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Gzy', '424 Eagan Pass', 'Turquoise', 'Windsor', 'Indigo', 'Crimson');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Archis', '14 Bashford Lane', 'Goldenrod', 'Grębów', 'Khaki', 'Mauv');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Hāla', '354 Helena Hill', 'Green', 'Shāhdādkot', 'Aquamarine', 'Purple');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Chitral', '763 Lerdahl Court', 'Puce', 'Baiyin', 'Indigo', 'Orange');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Liucheng', '096 Westport Pass', 'Pink', 'Vale de Figueira', 'Maroon', 'Violet');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Krajan Battal', '36217 Golf Course Road', 'Crimson', 'Jovellar', 'Turquoise', 'Khaki');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Itajuípe', '24929 Hermina Point', 'Violet', 'Palomoc', 'Green', 'Purple');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Tanjungampalu', '49 Lakewood Hill', 'Turquoise', 'Sepahua', 'Aquamarine', 'Mauv');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Dahuangwei', '5744 Corben Pass', 'Yellow', 'Jinqiao', 'Crimson', 'Violet');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('La Loma', '8971 Mockingbird Trail', 'Yellow', 'Carcassonne', 'Orange', 'Aquamarine');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Centre de Flacq', '44 Lukken Pass', 'Pink', 'Jiaqiao', 'Indigo', 'Puce');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Norrköping', '2 2nd Hill', 'Blue', 'Vila Nova', 'Blue', 'Maroon');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Požarevac', '13222 Onsgard Trail', 'Fuscia', 'Navais', 'Teal', 'Aquamarine');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Luanshya', '046 Pine View Street', 'Red', 'Udon Thani', 'Goldenrod', 'Green');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Dong’an', '7 Hagan Lane', 'Aquamarine', 'Kole', 'Teal', 'Pink');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Anliang', '36314 Oneill Terrace', 'Crimson', 'Gryaznovskoye', 'Goldenrod', 'Pink');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Vichuga', '8 Stoughton Park', 'Turquoise', 'Kropotkin', 'Khaki', 'Indigo');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Morshansk', '2 Spohn Plaza', 'Maroon', 'Yanglinshi', 'Pink', 'Fuscia');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Cesvaine', '74 American Ash Center', 'Yellow', 'Luoping', 'Indigo', 'Purple');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Muxagata', '128 Service Court', 'Turquoise', 'Rila', 'Orange', 'Blue');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Dadong', '8146 Rockefeller Park', 'Teal', 'Nassau', 'Violet', 'Turquoise');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Hamburg', '9 Maple Center', 'Mauv', 'Strömsund', 'Violet', 'Fuscia');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Kayima', '79759 Nancy Junction', 'Crimson', 'Крушево', 'Teal', 'Puce');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('San Juan', '248 Dennis Alley', 'Red', 'Alchevs’k', 'Indigo', 'Puce');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Cofimvaba', '22638 Buhler Way', 'Teal', 'Cipadung Timur', 'Pink', 'Teal');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Ban Phue', '551 Twin Pines Junction', 'Turquoise', 'Skovorodino', 'Pink', 'Red');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Chok Chai', '43 Judy Parkway', 'Violet', 'Roma', 'Red', 'Goldenrod');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Xiaoguai', '7838 Namekagon Avenue', 'Yellow', 'Pagaruša', 'Puce', 'Yellow');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Rio de Moinhos', '4876 Melrose Plaza', 'Aquamarine', 'Tiecun', 'Khaki', 'Teal');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Sawangan', '83 Pleasure Circle', 'Khaki', 'Kokkónion', 'Pink', 'Puce');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Le Mans', '25 Old Gate Center', 'Khaki', 'Armopa', 'Aquamarine', 'Orange');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Urshel’skiy', '24674 Talisman Alley', 'Purple', 'Pontevedra', 'Indigo', 'Mauv');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Shuvakish', '2 7th Parkway', 'Pink', 'Naikolan', 'Khaki', 'Maroon');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Qaxbaş', '480 Lyons Terrace', 'Yellow', 'Grijó', 'Puce', 'Maroon');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Linggou', '93587 Becker Terrace', 'Teal', 'Mazongling', 'Aquamarine', 'Khaki');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Barreiro', '5 Graedel Avenue', 'Orange', 'Cunén', 'Blue', 'Maroon');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Zorgo', '764 Moose Parkway', 'Red', 'Marapanim', 'Indigo', 'Aquamarine');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Yuanshanzi', '430 Atwood Parkway', 'Fuscia', 'Kitaibaraki', 'Violet', 'Orange');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Empangeni', '6 Lyons Street', 'Puce', 'Sirari', 'Pink', 'Yellow');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Huangshui', '16438 Anthes Plaza', 'Maroon', 'Zhongwei', 'Goldenrod', 'Maroon');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Jingxiyuan', '005 Colorado Lane', 'Fuscia', 'Cicurug', 'Blue', 'Aquamarine');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Panunggangan', '3152 Stang Street', 'Crimson', 'Olofström', 'Green', 'Teal');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Miami', '28873 Nancy Alley', 'Red', 'Yesan', 'Violet', 'Violet');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Morropón', '545 Elmside Crossing', 'Mauv', 'Guararema', 'Aquamarine', 'Maroon');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Castelo', '4 Maple Wood Road', 'Turquoise', 'Gulao', 'Indigo', 'Violet');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Santol', '9 Forest Dale Pass', 'Maroon', 'Toyama-shi', 'Aquamarine', 'Goldenrod');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Shanxia', '87128 Dayton Drive', 'Red', 'Llusco', 'Aquamarine', 'Maroon');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Xiongzhang', '05061 Sloan Lane', 'Orange', 'Hongqi Yingzi', 'Green', 'Pink');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Huanipaca', '21 Mccormick Drive', 'Violet', 'Kendari', 'Goldenrod', 'Aquamarine');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Ballybofey', '65186 Carey Junction', 'Blue', 'Dzyarzhynsk', 'Green', 'Puce');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Lexington', '84483 American Ash Avenue', 'Red', 'Almenara', 'Turquoise', 'Fuscia');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Efkarpía', '17 Goodland Drive', 'Maroon', 'Wunat', 'Blue', 'Aquamarine');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Chone', '3422 Melrose Lane', 'Purple', 'Merefa', 'Orange', 'Blue');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Blagoveshchenka', '05213 Namekagon Alley', 'Blue', 'Zhongtang', 'Purple', 'Teal');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('São João de Caparica', '649 Elmside Center', 'Mauv', 'Hualfín', 'Puce', 'Blue');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Chikeng', '8504 Cottonwood Hill', 'Pink', 'Barrī ash Sharqī', 'Green', 'Puce');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Kampungmasjid', '64623 Dottie Road', 'Goldenrod', 'Roanoke', 'Crimson', 'Aquamarine');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Qorovulbozor', '4 Express Pass', 'Red', 'Limonade', 'Turquoise', 'Indigo');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Pu’er', '0752 Moulton Drive', 'Khaki', 'Guanhães', 'Mauv', 'Green');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Soko', '7198 Loeprich Junction', 'Aquamarine', 'Vilar', 'Indigo', 'Violet');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Gueltat Zemmour', '59460 Talmadge Court', 'Goldenrod', 'Ráječko', 'Mauv', 'Goldenrod');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Huanuni', '54 Sullivan Trail', 'Aquamarine', 'Vabalninkas', 'Green', 'Aquamarine');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Yunping', '8395 Doe Crossing Park', 'Khaki', 'Jeminay', 'Orange', 'Goldenrod');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Vilar', '4 Westerfield Center', 'Yellow', 'Xiwang', 'Fuscia', 'Turquoise');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Espírito Santo do Pinhal', '055 Claremont Terrace', 'Puce', 'Lop', 'Puce', 'Red');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Kungshamn', '63593 Stang Place', 'Purple', 'Złocieniec', 'Indigo', 'Aquamarine');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Temayang', '1 Pennsylvania Crossing', 'Crimson', 'Kinkala', 'Red', 'Maroon');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Rentian', '545 Corry Drive', 'Purple', 'Thị Trấn Mường Lát', 'Yellow', 'Purple');
insert into carreras (descripcion, anios, resolucion, texto, imagen, nombre_carpeta) values ('Looc', '7527 Charing Cross Hill', 'Blue', 'Aserrío de Gariché', 'Orange', 'Turquoise');
