insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Guandiping', 1, 1, 1);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Foúrnoi', 2, 2, 2);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Dordrecht', 3, 3, 3);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Langsepan', 4, 4, 4);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Wangkung', 5, 5, 5);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Fovissste', 6, 6, 6);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Changyŏn', 7, 7, 7);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Kalinkavichy', 8, 8, 8);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Pskov', 9, 9, 9);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Kimch’aek-si', 10, 10, 10);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Emar', 11, 11, 11);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Mirosławiec', 12, 12, 12);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Shigongqiao', 13, 13, 13);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Bayshint', 14, 14, 14);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Ołpiny', 15, 15, 15);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Xinji', 16, 16, 16);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Pongol', 17, 17, 17);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Nanshan', 18, 18, 18);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Koška', 19, 19, 19);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('San Rafael Oriente', 20, 20, 20);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Murcia', 21, 21, 21);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Bořitov', 22, 22, 22);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Néa Palátia', 23, 23, 23);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Hällefors', 24, 24, 24);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Macia', 25, 25, 25);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Vesoul', 26, 26, 26);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Al Ghizlānīyah', 27, 27, 27);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Novoderevyankovskaya', 28, 28, 28);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Hangbu', 29, 29, 29);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Giraldo', 30, 30, 30);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Falköping', 31, 31, 31);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Racławice', 32, 32, 32);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Río Segundo', 33, 33, 33);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Pueblo Nuevo', 34, 34, 34);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Mahdalynivka', 35, 35, 35);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Härnösand', 36, 36, 36);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Ledeč nad Sázavou', 37, 37, 37);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Chambellan', 38, 38, 38);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Amagasaki', 39, 39, 39);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Nurmo', 40, 40, 40);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Al Jaghbūb', 41, 41, 41);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Vale Boeiro', 42, 42, 42);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Dudchany', 43, 43, 43);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('San Juan', 44, 44, 44);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Fuzhuang', 45, 45, 45);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Hingatungan', 46, 46, 46);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Ol Kalou', 47, 47, 47);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Oxelösund', 48, 48, 48);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Belgrade', 49, 49, 49);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Shangcai Zhongxing', 50, 50, 50);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Staraya Kupavna', 51, 51, 51);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Wuduhe', 52, 52, 52);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Zhengyu', 53, 53, 53);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Babasakhib', 54, 54, 54);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Ketara', 55, 55, 55);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Valle San Francisco', 56, 56, 56);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Montpellier', 57, 57, 57);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Dubovka', 58, 58, 58);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Ush-Tyube', 59, 59, 59);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Xinjiezhen', 60, 60, 60);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Vegachí', 61, 61, 61);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Kidatu', 62, 62, 62);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Lajeosa do Mondego', 63, 63, 63);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Nakhabino', 64, 64, 64);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Klonowa', 65, 65, 65);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Moroto', 66, 66, 66);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Pasto', 67, 67, 67);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Riangbao', 68, 68, 68);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Zhuxi', 69, 69, 69);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Araguari', 70, 70, 70);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Russkiy', 71, 71, 71);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Kusheriki', 72, 72, 72);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Banjar Jabejero', 73, 73, 73);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Filothéi', 74, 74, 74);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Petrovsk', 75, 75, 75);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Ebaye', 76, 76, 76);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Zungeru', 77, 77, 77);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Wonocolo', 78, 78, 78);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Qiaotou', 79, 79, 79);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Rokycany', 80, 80, 80);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Oakville', 81, 81, 81);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Sipeng', 82, 82, 82);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Rumenka', 83, 83, 83);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Zhangjiawo', 84, 84, 84);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Mojo', 85, 85, 85);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Zuhu', 86, 86, 86);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Bueng Samakkhi', 87, 87, 87);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Angoulême', 88, 88, 88);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Ajaccio', 89, 89, 89);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Dashiren', 90, 90, 90);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Pyrgetós', 91, 91, 91);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Tianning', 92, 92, 92);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Fatufaun', 93, 93, 93);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Cigeulis', 94, 94, 94);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Galátsi', 95, 95, 95);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Kayukembang', 96, 96, 96);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Радовиш', 97, 97, 97);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Sinarbakti', 98, 98, 98);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Lidingö', 99, 99, 99);
insert into materias (descripcion, carrera_id, anio_id, profesor_id) values ('Chulabhorn', 100, 100, 100);
