insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (1, 1, 1, 1, 1, 1, 'Pawing', 'Chat Trakan', '2022-05-05');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (2, 2, 2, 2, 2, 2, 'Philadelphia', 'Jinpanling', '2022-04-29');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (3, 3, 3, 3, 3, 3, 'Riangbao', 'Jiangkou', '2022-06-29');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (4, 4, 4, 4, 4, 4, 'Nikol’sk', 'Lushnjë', '2021-11-20');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (5, 5, 5, 5, 5, 5, 'Nungwi', 'São Bernardo do Campo', '2022-06-29');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (6, 6, 6, 6, 6, 6, 'Oesena', 'Saint-Ouen', '2022-09-01');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (7, 7, 7, 7, 7, 7, 'Pengulu', 'Baolong', '2022-01-13');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (8, 8, 8, 8, 8, 8, 'Lebak', 'Ambato', '2022-01-16');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (9, 9, 9, 9, 9, 9, 'Yoshii', 'Bento Gonçalves', '2021-11-16');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (10, 10, 10, 10, 10, 10, 'Talalayivka', 'Delaware', '2022-04-30');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (11, 11, 11, 11, 11, 11, 'Aveiras de Cima', 'Tomingad', '2021-11-29');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (12, 12, 12, 12, 12, 12, 'Kupino', 'Jinping', '2021-10-18');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (13, 13, 13, 13, 13, 13, 'Sankt Lorenzen im Mürztal', 'Sexiong', '2022-03-22');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (14, 14, 14, 14, 14, 14, 'Stary Sącz', 'Consolación del Sur', '2022-09-01');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (15, 15, 15, 15, 15, 15, 'Ciparakan', 'Pehčevo', '2022-01-31');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (16, 16, 16, 16, 16, 16, 'Souto de Cima', 'Quintão', '2022-03-31');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (17, 17, 17, 17, 17, 17, 'Kåge', 'Abdurahmoni Jomí', '2021-10-10');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (18, 18, 18, 18, 18, 18, 'Şabāḩ as Sālim', 'Shancheng', '2021-10-16');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (19, 19, 19, 19, 19, 19, 'Sedatiagung', 'Santa Maria', '2022-02-15');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (20, 20, 20, 20, 20, 20, 'Quận Năm', 'Doug An', '2022-06-14');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (21, 21, 21, 21, 21, 21, 'San Juan de Limay', 'General Conesa', '2021-09-28');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (22, 22, 22, 22, 22, 22, 'Žitenice', 'Kladi', '2022-07-10');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (23, 23, 23, 23, 23, 23, 'Shuitai', 'Lukovica pri Domžalah', '2021-12-02');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (24, 24, 24, 24, 24, 24, 'Kanashevo', 'Duantan', '2022-05-18');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (25, 25, 25, 25, 25, 25, 'Huandiqiao', 'Shuangxiqiao', '2021-11-24');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (26, 26, 26, 26, 26, 26, 'Manhush', 'Jalinan', '2022-02-20');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (27, 27, 27, 27, 27, 27, 'Yangji', 'Xitou', '2022-07-01');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (28, 28, 28, 28, 28, 28, 'Madette', 'Druju', '2022-02-17');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (29, 29, 29, 29, 29, 29, 'Kamenický Šenov', 'Kirzhach', '2022-05-11');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (30, 30, 30, 30, 30, 30, 'Muḩambal', 'Fleury-les-Aubrais', '2022-04-16');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (31, 31, 31, 31, 31, 31, 'Skärhamn', 'Moulay Bouchta', '2022-05-23');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (32, 32, 32, 32, 32, 32, 'Kurmanayevka', 'Tumbes', '2022-03-26');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (33, 33, 33, 33, 33, 33, 'Malati', 'St. Anton an der Jeßnitz', '2022-08-01');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (34, 34, 34, 34, 34, 34, 'Rizal', 'Kampunganyar', '2022-05-29');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (35, 35, 35, 35, 35, 35, 'Ludvika', 'Shimabara', '2021-10-15');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (36, 36, 36, 36, 36, 36, 'Kalmar', 'Kinalansan', '2022-08-05');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (37, 37, 37, 37, 37, 37, 'Batasan Bata', 'Cheyenne', '2022-04-20');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (38, 38, 38, 38, 38, 38, 'Naḥf', 'Norton', '2021-09-23');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (39, 39, 39, 39, 39, 39, 'Mahābād', 'Patong', '2022-06-16');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (40, 40, 40, 40, 40, 40, 'Sembungan Kidul', 'Toyooka', '2021-12-09');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (41, 41, 41, 41, 41, 41, 'Trhové Sviny', 'Lebedyn', '2021-11-16');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (42, 42, 42, 42, 42, 42, 'Bautista', 'Bulualto', '2022-02-27');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (43, 43, 43, 43, 43, 43, 'Rumat Heib', 'Citasuk', '2021-09-26');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (44, 44, 44, 44, 44, 44, 'Nikol’skoye', 'El Carmen', '2021-12-22');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (45, 45, 45, 45, 45, 45, 'Sebewe', 'Moses', '2022-06-26');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (46, 46, 46, 46, 46, 46, 'Novallas', 'Yaroslavskaya', '2021-11-26');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (47, 47, 47, 47, 47, 47, 'Austin', 'Hveragerði', '2022-02-04');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (48, 48, 48, 48, 48, 48, 'Évreux', 'Camilo Aldao', '2021-12-26');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (49, 49, 49, 49, 49, 49, 'Baoshan', 'Dalaba', '2022-03-26');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (50, 50, 50, 50, 50, 50, 'Luxi', 'Yuanyang Zhen', '2022-07-26');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (51, 51, 51, 51, 51, 51, 'Ujar', 'Chenfang', '2022-05-02');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (52, 52, 52, 52, 52, 52, 'Podhum', 'Toledo', '2022-04-02');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (53, 53, 53, 53, 53, 53, 'Phon Charoen', 'Tapakrejo', '2021-11-06');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (54, 54, 54, 54, 54, 54, 'Duraznopampa', 'Dajianchang', '2021-11-20');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (55, 55, 55, 55, 55, 55, 'Euclides da Cunha', 'Łopuszna', '2022-04-20');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (56, 56, 56, 56, 56, 56, 'Panique', 'Baltasar Brum', '2021-10-01');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (57, 57, 57, 57, 57, 57, 'Nagua', 'Ksour Essaf', '2022-07-13');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (58, 58, 58, 58, 58, 58, 'Tarikolot', 'La Plaine-Saint-Denis', '2022-08-01');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (59, 59, 59, 59, 59, 59, 'Montevista', 'Ivanovskoye', '2021-10-22');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (60, 60, 60, 60, 60, 60, 'Buzen', 'Cabrobó', '2022-03-10');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (61, 61, 61, 61, 61, 61, 'Pag', 'Lipci', '2021-12-14');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (62, 62, 62, 62, 62, 62, 'Naukot', 'Pak Phli', '2022-02-13');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (63, 63, 63, 63, 63, 63, 'Maxixe', 'Huangyuan Chengguanzhen', '2022-01-22');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (64, 64, 64, 64, 64, 64, 'Tucaní', 'Las Animas', '2022-03-24');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (65, 65, 65, 65, 65, 65, 'Aubenas', 'Rancaseneng', '2021-11-13');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (66, 66, 66, 66, 66, 66, 'Jinhua', 'Pantai', '2022-01-31');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (67, 67, 67, 67, 67, 67, 'San Juan de Colón', 'Tower', '2022-02-12');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (68, 68, 68, 68, 68, 68, 'Calimita', 'Arroio do Meio', '2021-10-21');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (69, 69, 69, 69, 69, 69, 'Rautjärvi', 'Yeping', '2022-02-23');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (70, 70, 70, 70, 70, 70, 'Turiys’k', 'Gjilan', '2022-03-10');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (71, 71, 71, 71, 71, 71, 'Alvito de São Pedro', 'Geputan', '2021-12-21');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (72, 72, 72, 72, 72, 72, 'Miskolc', 'Bauchi', '2021-11-01');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (73, 73, 73, 73, 73, 73, 'Lenger', 'Yaxi', '2022-09-02');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (74, 74, 74, 74, 74, 74, 'Kaura Namoda', 'Xianghu', '2022-09-11');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (75, 75, 75, 75, 75, 75, 'Taung', 'Waitangi', '2022-07-30');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (76, 76, 76, 76, 76, 76, 'Laḩij', 'Kadaka', '2022-03-29');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (77, 77, 77, 77, 77, 77, 'Kalangan', 'Nuoxizhi', '2021-10-07');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (78, 78, 78, 78, 78, 78, 'Bastia', 'Áno Kopanákion', '2022-06-21');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (79, 79, 79, 79, 79, 79, 'Itoman', 'Liangdang Chengguanzhen', '2022-03-03');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (80, 80, 80, 80, 80, 80, 'Thị Trấn Phú Mỹ', 'Funabashi', '2021-10-14');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (81, 81, 81, 81, 81, 81, 'Fu’an', 'Lourdes', '2021-12-08');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (82, 82, 82, 82, 82, 82, 'El Tambo', 'Santo Domingo Oeste', '2022-03-20');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (83, 83, 83, 83, 83, 83, 'Frýdlant', 'Novoarkhanhel’s’k', '2022-08-22');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (84, 84, 84, 84, 84, 84, 'Fangtian', 'Jember', '2022-06-09');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (85, 85, 85, 85, 85, 85, '‘Izrā', 'Serra Talhada', '2022-05-05');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (86, 86, 86, 86, 86, 86, 'Taohuajiang', 'Blinsung', '2021-09-25');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (87, 87, 87, 87, 87, 87, 'Merke', 'Shangfang', '2022-03-27');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (88, 88, 88, 88, 88, 88, 'Daliuhao', 'Aurora', '2021-11-18');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (89, 89, 89, 89, 89, 89, 'Kiraman', 'Batobato', '2022-06-13');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (90, 90, 90, 90, 90, 90, 'Vodstroy', 'Farsta', '2022-08-24');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (91, 91, 91, 91, 91, 91, 'Wuṯahpūr', 'Yuetang', '2022-02-24');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (92, 92, 92, 92, 92, 92, 'Kasreman', 'Leuwayang', '2021-12-19');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (93, 93, 93, 93, 93, 93, 'Tentúgal', 'Bakov nad Jizerou', '2022-02-16');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (94, 94, 94, 94, 94, 94, 'Jianshe', 'Randu', '2022-06-25');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (95, 95, 95, 95, 95, 95, 'Rēzekne', 'Kangān', '2021-12-20');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (96, 96, 96, 96, 96, 96, 'Farroupilha', 'Nazca', '2022-04-04');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (97, 97, 97, 97, 97, 97, 'Sant Julià de Lòria', 'Mucifal', '2021-11-13');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (98, 98, 98, 98, 98, 98, 'Colca', 'Saubara', '2022-03-31');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (99, 99, 99, 99, 99, 99, 'Frei', 'Kandahār', '2021-12-10');
insert into programas (sede_id, carrera_id, anio_id, materia_id, comision_id, profesor_id, nombrearchivo, ruta, fechaentrega) values (100, 100, 100, 100, 100, 100, 'Huasta', 'Chizhou', '2022-04-18');
