insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Voronezh', '131 Wayridge Road', '15', 'Pule', 'Crimson');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Marmashen', '4 Arizona Hill', '5866', 'Cervantes', 'Puce');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Cachimayo', '72 Del Mar Crossing', '9974', 'Xinxing', 'Green');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Jinhe', '889 Vahlen Parkway', '5', 'Belo Blato', 'Mauv');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Damāvand', '4773 Cardinal Hill', '06303', 'Merlo', 'Orange');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Velká nad Veličkou', '8986 Briar Crest Avenue', '77', 'Chikola', 'Yellow');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Maurole', '767 Ridgeway Lane', '51846', 'Kota Kinabalu', 'Khaki');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Ropa', '2326 Steensland Terrace', '5', 'Hobo', 'Violet');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Nueva Guadalupe', '2119 Vernon Terrace', '70', 'Ordzhonikidzevskaya', 'Turquoise');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Limoges', '2 Armistice Parkway', '05880', 'Pétionville', 'Goldenrod');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Grabovci', '59406 Old Gate Court', '9', 'Fílla', 'Red');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Gur’yevsk', '93 Luster Point', '4', 'Bom Jesus dos Perdões', 'Violet');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Neftegorsk', '2638 Shopko Place', '8049', 'Dampit Satu', 'Violet');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Gempolan Wetan', '169 Portage Parkway', '2', 'Falun', 'Puce');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Longlisuo', '45623 Kennedy Crossing', '6160', 'Dřiteň', 'Orange');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Alor Setar', '0 Ilene Circle', '55', 'Wólka Pełkińska', 'Yellow');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Petrich', '9350 Algoma Way', '965', 'Zhongdeng', 'Violet');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Sawoi', '2 Moland Court', '2', 'Sievi', 'Maroon');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Turangi', '43348 Emmet Terrace', '12', 'Ulee Gle', 'Mauv');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Xilian', '82 Memorial Hill', '9', 'East Migpulao', 'Mauv');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Richard-Toll', '930 Merry Trail', '9380', 'Pridonskoy', 'Pink');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Bangunsari', '103 Dapin Place', '854', 'Umuquena', 'Khaki');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Lyon', '0 Tennessee Center', '2524', 'Mauraro', 'Fuscia');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Rathangan', '7 Nova Trail', '937', 'Feijó', 'Purple');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Tambakbaya', '530 Laurel Park', '3291', 'Alaverdi', 'Maroon');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Krasnyy Yar', '52 Rusk Pass', '1', 'Oyama', 'Goldenrod');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Atlanta', '66 American Parkway', '2', 'Bang Rak', 'Green');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Jagdaqi', '138 Northwestern Plaza', '1577', 'Talun', 'Crimson');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Chunjing', '56 Erie Point', '02248', 'Korczyna', 'Green');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Badar', '6 Emmet Pass', '83', 'Ipueiras', 'Yellow');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Tsotsin-Yurt', '8038 Hoepker Alley', '600', 'Canha', 'Orange');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('São Bernardo do Campo', '390 Arrowood Plaza', '82', 'Machachi', 'Yellow');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Yahe', '59317 Oriole Terrace', '41786', 'Shibajiazi', 'Crimson');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Qinling Jieban', '65086 Lyons Court', '42', 'Xylotymbou', 'Teal');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Megalópoli', '8283 Lighthouse Bay Trail', '1', 'Lyubech', 'Fuscia');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Banjarbaru', '7 Graedel Terrace', '078', 'Velké Bílovice', 'Khaki');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Viana', '5920 Badeau Trail', '93', 'Kribi', 'Mauv');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Vukojevci', '3 Elmside Way', '4', 'Ban Phan Don', 'Violet');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Dzhalilabad', '5 Calypso Avenue', '51273', 'Dera Murād Jamāli', 'Violet');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Janowice', '1 Erie Trail', '98', 'Habiganj', 'Purple');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Huangliu', '95 Butternut Point', '53899', 'Taifu', 'Fuscia');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Wilmington', '4541 Laurel Junction', '0', 'Xinwan', 'Fuscia');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Sainte-Agathe-des-Monts', '62407 Sauthoff Court', '9294', 'Caaguazú', 'Blue');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Margasana', '9553 Jackson Point', '9425', 'Pa Phayom', 'Green');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Sukamaju', '9111 Hanson Hill', '1760', 'Nantes', 'Orange');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Catalão', '65 Sullivan Park', '341', 'Yeşilköy', 'Violet');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Sanana', '18 Grover Road', '6', 'Bartolomé Masó', 'Green');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Saidpur', '25925 Blackbird Terrace', '9', 'Pasargunung', 'Red');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Pingyang', '4038 Graceland Court', '89840', 'Hotaka', 'Pink');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Malabag', '61 Sommers Pass', '5', 'Santa Tecla', 'Puce');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Tangkilsari', '83 Colorado Plaza', '4456', 'Wumahe', 'Puce');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Los Cedrales', '5175 Waubesa Pass', '47262', 'La Vega', 'Maroon');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Junxi', '7560 Fordem Court', '46101', 'Vittoriosa', 'Red');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Taluksangay', '27220 Schiller Pass', '3680', 'Dolní Černilov', 'Khaki');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Ozalj', '5 Browning Street', '66566', 'San Jose', 'Pink');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Sembon', '6800 Welch Trail', '72', 'Kura', 'Teal');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Ozerne', '0242 Claremont Junction', '495', 'Haputale', 'Khaki');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Lümeng', '8 Mockingbird Way', '712', 'Bangluo', 'Maroon');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Dallas', '5202 Golf View Center', '40887', 'Mirny', 'Maroon');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Mundão', '113 Lillian Place', '05', 'Cerro Azul', 'Puce');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Saboyá', '29294 Towne Avenue', '61949', 'Kebonbencoy', 'Crimson');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Haoba', '777 Darwin Trail', '35498', 'Cacheu', 'Yellow');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Nanmu', '8 American Place', '768', 'Fenlu', 'Fuscia');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Lyeskawka', '99413 Bellgrove Center', '0', 'Stockholm', 'Red');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Emmen', '255 Calypso Pass', '213', 'Baton Rouge', 'Goldenrod');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Poiares', '96 Kings Pass', '470', 'Hexing', 'Goldenrod');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Bangjun', '17703 Randy Parkway', '62', 'Johor Bahru', 'Maroon');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Yongxing', '47 Northwestern Terrace', '94620', 'Agbor', 'Indigo');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Mosoc Llacta', '3 Waubesa Avenue', '1', 'Phước An', 'Puce');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Sparwood', '25 Delladonna Crossing', '5412', 'San Martin', 'Puce');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Shanmuqiao', '1 Blue Bill Park Street', '9', 'Sengeti', 'Yellow');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Damasak', '9 Texas Place', '652', 'Moholm', 'Puce');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('San Diego', '93 Lunder Trail', '422', 'San Isidro', 'Blue');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Laiguangying', '95917 Cordelia Way', '2734', 'Tartu', 'Yellow');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Soi Dao', '98 Melody Street', '4845', 'Igreja', 'Mauv');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Castedo', '67 Swallow Place', '738', 'Panimbang', 'Pink');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Kaliprak', '4 John Wall Park', '7116', 'Nigel', 'Yellow');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Xinshi', '4910 Mockingbird Point', '2519', 'La Cesira', 'Maroon');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Heicheng', '85 American Ash Hill', '98', 'Embarcación', 'Blue');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Katy', '246 Lakewood Crossing', '9187', 'Mucifal', 'Red');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Pār Naogaon', '65 Evergreen Trail', '19', 'Mizunami', 'Puce');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Cueto', '743 Waywood Terrace', '55', 'Vicuña', 'Purple');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Donskoye', '6641 Alpine Avenue', '11', 'Kuala Terengganu', 'Khaki');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Shiyan', '3545 Garrison Place', '9', 'Ūdalah', 'Crimson');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Les Abymes', '486 Goodland Road', '8978', 'Uppsala', 'Red');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Acul du Nord', '2173 Erie Street', '733', 'Shuangxi', 'Goldenrod');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Serednye', '410 Hovde Way', '7', 'Santo Antônio de Posse', 'Fuscia');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Catbalogan', '12 Buhler Place', '50565', 'Genisséa', 'Turquoise');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Ancasti', '65295 Bobwhite Street', '41404', 'Santa Luzia', 'Teal');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Benito Juarez', '28262 Elka Place', '960', 'Santa Fé do Sul', 'Goldenrod');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Santa Cruz', '0 Hoard Center', '1', 'Södertälje', 'Fuscia');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Głogówek', '654 Mandrake Plaza', '26953', 'Guanaja', 'Yellow');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Arvika', '9 Coolidge Court', '7132', 'Shanhou', 'Purple');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Lyon', '88 Northfield Circle', '90', 'Bungtiang Barat', 'Mauv');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Oni', '1051 Fallview Trail', '93', 'Ciudad Arce', 'Fuscia');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Nový Bydžov', '43916 Kensington Pass', '93', 'Songgui', 'Indigo');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Nanjiao', '5 Melvin Court', '08', 'Damaturu', 'Purple');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Qingyun', '00271 Little Fleur Way', '16', 'Marne-la-Vallée', 'Maroon');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Hưng Nguyên', '9787 Westerfield Street', '88302', 'Cijoho', 'Red');
insert into sedes (descripcion, calle, numero, ciudad, sedeimagen) values ('Shuikou', '06 Old Gate Drive', '10', '‘Ayn al Bayḑā', 'Purple');
